# Generated by Django 4.1 on 2023-10-24 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('password', models.CharField(default='default_password', max_length=128)),
                ('adding_data', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
